
[core]
telemetry = false  # disables telemetry

[work_queues]
type = "redis"  # use Redis for work queues
redis_connection_url = "redis://localhost:6379/0"  # your Redis connection string
[server]
[server.database]
connection_url = "postgresql+asyncpg://postgres:arka@localhost:5434/prefect"
timeout = 600

[logging]
level = "DEBUG"
