
[core]
telemetry = false # disables telemetry

# [server.events]
# # Messaging broker implementation
# messaging_broker = "prefect_redis.messaging"

# # Messaging cache implementation
# messaging_cache = "prefect_redis.messaging"
[server]
[server.database]
connection_url = "postgresql+asyncpg://postgres:arka@localhost:5434/prefect"
timeout = 600

[logging]
level = "DEBUG"
